import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavTop from "./components/NavBar/NavTop";
import { ThemeProvider } from "@/components/Theme-provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavTop />
          <div className=" mt-14 mx-auto p-5 top-14">
          {children}
          </div>
         
        </ThemeProvider>
      </body>
    </html>
  );
}
